### PR TITLE
Create sys_select.h

### PR DESCRIPTION
**Pull request by traversaro**
Fix https://github.com/iit-danieli-joint-lab/idjl-gcc-vxworks/issues/24

### CODE REVIEW

**Comment by traversaro** [comment]
fyi @strongly-typed

**Comment by strongly-typed** [comment]
Thanks for the quick fix. Seems to work. Did not compile anything with it yet.

The next copy command

https://github.com/iit-danieli-joint-lab/idjl-gcc-vxworks/blob/6420f4629c2c68e4b0282555de37c34b4db735c3/build_idjl_gcc_vxworks.sh#L135

does not work.


```
make[1]: Leaving directory '/root/idjl-gcc-vxworks/build-gcc'
cp: cannot stat '/root/idjl-gcc-vxworks/wrs-vxworks-headers/i586-wrs-vxworks/sys-include/wrn/coreip/net/uio.h': No such file or directory
FAILED COMMAND: cp ${SCRIPTPATH}/wrs-vxworks-headers/i586-wrs-vxworks/sys-include/wrn/coreip/net/uio.h $INSTALL_PATH/include/i586-wrs-vxworks/idjl-include/sys/uio.h
```

The file `uio.h` is present here:

```
root@debian:~/idjl-gcc-vxworks# find . -iname "uio.h"
./install/i586-wrs-vxworks/wrn/coreip/net/uio.h
./install/i586-wrs-vxworks/sys-include/wrn/coreip/net/uio.h
./wrs-vxworks-headers/include/net/uio.h
./wrs-vxworks-headers/wind_base/target/h/net/uio.h
./wrs-vxworks-headers/sys-include/wrn/coreip/net/uio.h
./gccdist/WindRiver/vxworks-6.3/target/h/wrn/coreip/net/uio.h
```

Running in fresh a Debian 9 i386 VM for testing:
```
root@debian:~/idjl-gcc-vxworks# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.13 (stretch)
Release:	9.13
Codename:	stretch
```

**Comment by traversaro** [comment]
Thanks, probably this was a regression done in https://github.com/iit-danieli-joint-lab/idjl-gcc-vxworks/pull/13 as I had manually copied the file in https://github.com/iit-danieli-joint-lab/idjl-gcc-vxworks/releases/tag/v0.3.2 instead of re-running the script. I am a bit out of time to fix this, but you could check the content of `$INSTALL_PATH/include/i586-wrs-vxworks/idjl-include/sys/uio.h` in  https://github.com/iit-danieli-joint-lab/idjl-gcc-vxworks/releases/tag/v0.3.2 and compare it among the possible options you listed:
~~~
root@debian:~/idjl-gcc-vxworks# find . -iname "uio.h"
./install/i586-wrs-vxworks/wrn/coreip/net/uio.h
./install/i586-wrs-vxworks/sys-include/wrn/coreip/net/uio.h
./wrs-vxworks-headers/include/net/uio.h
./wrs-vxworks-headers/wind_base/target/h/net/uio.h
./wrs-vxworks-headers/sys-include/wrn/coreip/net/uio.h
./gccdist/WindRiver/vxworks-6.3/target/h/wrn/coreip/net/uio.h
~~~
if it matches one of the files, we know which version we can use to fix the script.

**Comment by strongly-typed** [comment]
All files are equal ;-)

```
root@debian:~/idjl-gcc-vxworks# find . -iname "uio.h" -exec sha1sum {} \;
7aac3bc6d04737c5da2ab494be7314517d0d5876  ./install/wrs-vxworks-headers/include/net/uio.h
7aac3bc6d04737c5da2ab494be7314517d0d5876  ./install/wrs-vxworks-headers/wind_base/target/h/net/uio.h
7aac3bc6d04737c5da2ab494be7314517d0d5876  ./install/wrs-vxworks-headers/sys-include/wrn/coreip/net/uio.h
7aac3bc6d04737c5da2ab494be7314517d0d5876  ./install/i586-wrs-vxworks/wrn/coreip/net/uio.h
7aac3bc6d04737c5da2ab494be7314517d0d5876  ./install/i586-wrs-vxworks/sys-include/wrn/coreip/net/uio.h
7aac3bc6d04737c5da2ab494be7314517d0d5876  ./wrs-vxworks-headers/include/net/uio.h
7aac3bc6d04737c5da2ab494be7314517d0d5876  ./wrs-vxworks-headers/wind_base/target/h/net/uio.h
7aac3bc6d04737c5da2ab494be7314517d0d5876  ./wrs-vxworks-headers/sys-include/wrn/coreip/net/uio.h
7aac3bc6d04737c5da2ab494be7314517d0d5876  ./gccdist/WindRiver/vxworks-6.3/target/h/wrn/coreip/net/uio.h
```

**Comment by traversaro** [comment]
Sorry, I do not know what could be the problem. Anyhow, I think we can merge this.

**Pull request merged**
